feat: trigger the documentation only when changed

diff --git a/.readthedocs.yaml b/.readthedocs.yaml
--- a/.readthedocs.yaml
+++ b/.readthedocs.yaml
@@ -6,10 +6,21 @@
 version: 2
 
 build:
-  os: ubuntu-22.04
+  os: ubuntu-24.04
   tools:
-    python: "3.11"
-
+    python: "3.14"
+    jobs:
+      post_checkout:
+        # https://docs.readthedocs.io/en/stable/build-customization.html#cancel-build-based-on-a-condition
+        #
+        # Cancel building pull requests when there aren't changed in the docs directory.
+        # 183 is a special exit code on Read the Docs that will cancel the build immediately.
+        - |
+          if [ "$READTHEDOCS_VERSION_TYPE" = "external" ] && git diff --quiet origin/main -- docs/ .readthedocs.yml requirements/docs.txt;
+          then
+            echo "No changes to docs/ - exiting the build.";
+            exit 183;
+          fi
 mkdocs:
   configuration: docs/mkdocs.yml
 
